version: "2.4"

services:

  backend:
    build:
      context: ./
      dockerfile: containers/controller-proxy/Dockerfile
    restart: always
    environment:
      - "CONTROLLER_SSH_PORT"
      - "CONTROLLER_PROXY_HOSTNAME"
      - "CONTROLLER_PROXY_SSH_PORT"

  controller:
    build:
      context: ./
      dockerfile: containers/controller/Dockerfile
    restart: always
    volumes:
      - "/usr/share/hutbee/temperatures.csv:/app/temperatures.csv"
    devices:
      - "/dev/i2c-1"

  controller-wifi:
    build:
      context: ./
      dockerfile: containers/controller-wifi/Dockerfile
    restart: always
    environment:
      - "BACKEND_HOSTNAME"
    privileged: true
