version: "2.4"

services:

  backend:
    build:
      context: ./
      dockerfile: containers/backend-proxy/Dockerfile
    environment:
      - "CONTROLLER_SSH_PORT"
      - "CONTROLLER_PROXY_HOSTNAME"
      - "CONTROLLER_PROXY_SSH_PORT"
    restart: always

  controller:
    build:
      context: ./
      dockerfile: containers/controller/Dockerfile
    restart: always
    devices:
      - "/dev/i2c-1"

