version: "2.4"

services:

  traefik:
    image: traefik:v2.0
    command: --providers.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  hutbee:
    image: httpd
    labels:
      - "traefik.http.routers.hutbee.rule=Host(`${HOSTNAME}`)"
