version: "2.4"

services:

  traefik:
    image: traefik:v2.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/acme.json:/acme.json

  db:
    image: mongo:4
    restart: always
    volumes:
      - mongo-db:/data/db
      - mongo-configdb:/data/configdb
    environment:
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}"
    mem_limit: 1g
    mem_reservation: 1g
    command: "--wiredTigerCacheSizeGB 1.0"

  frontend:
    build:
      context: .
      dockerfile: containers/frontend/Dockerfile
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-http.entrypoints=http"
      - "traefik.http.routers.frontend-http.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.frontend-http.middlewares=frontend-redirect@docker"
      - "traefik.http.middlewares.frontend-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.frontend-https.entrypoints=https"
      - "traefik.http.routers.frontend-https.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.frontend-https.tls.certResolver=letsencrypt"

  backend:
    build:
      context: .
      dockerfile: containers/backend/Dockerfile
    restart: always
    environment:
      - "HUTBEE_PRODUCTION=set"
      - 'MONGO_PASSWORD'
      - "MONGO_USERNAME"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-http.entrypoints=http"
      - "traefik.http.routers.backend-http.rule=Host(`backend.${HOSTNAME}`)"
      - "traefik.http.routers.backend-http.middlewares=backend-redirect@docker"
      - "traefik.http.middlewares.backend-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.backend-https.entrypoints=https"
      - "traefik.http.routers.backend-https.rule=Host(`backend.${HOSTNAME}`)"
      - "traefik.http.routers.backend-https.tls.certResolver=letsencrypt"

volumes:
  mongo-db:
  mongo-configdb:
