version: "2.4"

services:

  backend:
    build:
      context: ./
      dockerfile: containers/controller-proxy/Dockerfile
    restart: always
    environment:
      - "CONTROLLER_SSH_PORT"
      - "CONTROLLER_PROXY_HOSTNAME"
      - "CONTROLLER_PROXY_SSH_PORT"
      - "RABBITMQ_PORT"
      - "RABBITMQ_MGMT_PORT"

  controller:
    build:
      context: ./
      dockerfile: containers/controller/Dockerfile
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_USER"
      - "RABBITMQ_DEFAULT_PASS"
    volumes:
      - "/usr/share/hutbee/temperatures.csv:/app/temperatures.csv"
    devices:
      - "/dev/i2c-1"

  messaging:
    image: rabbitmq:3-management
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_USER"
      - "RABBITMQ_DEFAULT_PASS"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq:
